services:
  - type: web
    name: Facial Expression Recognition
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PORT
        value: 10000
    pythonVersion: 3.10.12
